# Generated by Django 4.1.7 on 2023-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=400)),
                ("ingrediens", models.CharField(max_length=800)),
                ("prix", models.IntegerField(default=0)),
                ("vegetariens", models.BooleanField(default=False)),
            ],
        ),
    ]
