# Generated by Django 4.1.7 on 2023-03-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="test",
        ),
    ]
