# Generated by Django 4.1.7 on 2023-03-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_delete_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pizza",
            old_name="ingrediens",
            new_name="ingredients",
        ),
        migrations.RenameField(
            model_name="pizza",
            old_name="vegetariens",
            new_name="vegetarienne",
        ),
    ]
